coverage:
  status:
    project:
      default:
        informational: true
        target: 80%
    patch:
      default:
        informational: true
        target: 80%
github_checks:
  annotations: false
