name: quality

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint_and_test:
    name: lint_and_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set_up_rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: cache_cargo_registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: cache_cargo_index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: cache_cargo_build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: check_formatting_with_rustfmt
        run: cargo fmt -- --check

      - name: run_clippy
        run: cargo clippy -- -D warnings

      - name: run_tests
        run: cargo test --verbose
